# Generated by Django 3.1.7 on 2021-03-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description_long', models.TextField()),
                ('description_short', models.TextField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('slug', models.SlugField(unique=True)),
                ('price_marketing', models.FloatField()),
                ('price_marketing_promotion', models.FloatField(default=0)),
                ('type', models.CharField(choices=[('V', 'Variance'), ('S', 'Simple')], default='V', max_length=1)),
            ],
        ),
    ]
