# Generated by Django 3.1.7 on 2021-03-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='qtd_total',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
